name: flutter_clone_cli
description: A CLI tool to create Flutter projects from custom templates
version: 1.0.0
repository: https://github.com/ibrahimelnemrtasawk-dev/flutter_clone_cli

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  yaml: ^3.1.2
  mason_logger: ^0.2.14

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  ftcreate: main
